# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      LNT_API_URL: http://192.168.1.119:3000
      LNT_API_SYNC_KEY: pon-un-secreto-largo-y-raro

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - server


