# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      LNT_API_URL: http://192.168.1.119:3000
      LNT_API_SYNC_KEY: pon-un-secreto-largo-y-raro
    ports:
      - 3040:3040


